artifact_location: file:C:/Users/Dustin/Projects/energy-forcaster/backend/training/40c3d74559cace5bd3bcdf7268a1033cbf3c0f59/0
creation_time: 1774856273449
experiment_id: '0'
last_update_time: 1774856273449
lifecycle_stage: active
name: Default
workspace: default
